### PR TITLE
Adds Name prefix for Muerte and Yobannoe dno

### PR DESCRIPTION
**Pull request by Dimiikou**
Muerte -> Calderon Kartell
Yobannoe dno -> Kerzakov 

(Both are 2 new blacklist modifiers)

### CODE REVIEW

**Comment by paulzhng** [comment]
These changes seem too specific to me. Please explain the meaning behind those modifiers and in which way they could be beneficial for other factions outside the one this change is targeted at.

**Comment by Dimiikou** [comment]
Yobannoe dno
-
In the Kerzakov, we've created a new team, named [Prigovor tsarya] which can reach up to 5 users.
Those 5 members are specified to deal with users on the blacklist, having the modifier [Yobannoe dno].
Because of this regulation, it's a great comfort feature, and would reduce lots of failures.
(Members which aren't part of the Prigivor tsarya are not allowed to deal with that kind of Blacklist)

Muerte
-
The regulation is almost the same as the one from Yobannoe dno, and brings up the same arguments.

**Comment by Dimiikou** [comment]
Beneficial for other factions is, that the chance the regulation from those two modifiers will be hurt less.
Cause that, discussions and complains in the public channels are getting reduced, and it's less work for the Leaders

**Comment by paulzhng** [comment]
I'd like to make it more non-specific to factions or more adjustable. This is too specific for my taste.

**Comment by Dimiikou** [comment]
Understandable

**Pull request closed without merging**
