### PR TITLE
Fixes wrong regex usage

### PR DESCRIPTION
**Pull request by Dimiikou**
d+ stands for  a number, but in this part the text is always "price$"

Need this change to get group(5) out of this Pattern

### CODE REVIEW

**Comment by paulzhng** [comment]
The missing escape of the `|` is a good catch although I don't agree with changing `\d` to `.` as the `$` sign is already in the pattern

**Comment by Dimiikou** [comment]
So like this?

**Review by paulzhng — APPROVED** [review]
LGTM if you need this for another project

**Comment by Dimiikou** [comment]
Yes, next pull request will follow

**Pull request merged**
